/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package COMP3111Lab1;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}

public static void main(String[] args){
	System.out.println("Hello World!");
}